version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: jitterbit-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_aqui
      POSTGRES_DB: jitterbit_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: